// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkghalgyuxgzktcaxzht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZ2hhbGd5dXhnemt0Y2F4emh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTY2MTcsImV4cCI6MjA3NDI3MjYxN30.Szg9SXKdJyKKrYSSQCmjuZB8cRdZOb1ImrlDvRhRSLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});